# Get all genres
GET https://ash-book-review.onrender.com/genres HTTP/1.1

# Get a single genre by ID
###
GET https://ash-book-review.onrender.com/genres/{id} HTTP/1.1

# Create a new genre
###
POST https://ash-book-review.onrender.com/genres HTTP/1.1
Content-Type: application/json

{
  "genreName": "Dystopian",
  "genreDescription": "A genre that explores social and political structures in a dark and often oppressive future."
}

# Update a genre
###
PUT https://ash-book-review.onrender.com/genres/669b06759205634a6d656697 HTTP/1.1
Content-Type: application/json

{
  "genreName": "Science Fiction",
  "genreDescription": "Fiction dealing with imaginative and futuristic concepts."
}

# Delete a genre
###
DELETE https://ash-book-review.onrender.com/genres/{id} HTTP/1.1
