# Get all reviewers
GET https://ash-book-review.onrender.com/reviewers HTTP/1.1

# Get a single reviewer by ID
###
GET https://ash-book-review.onrender.com/reviewers/{id} HTTP/1.1

# Create a new reviewer
###
POST https://ash-book-review.onrender.com/reviewers HTTP/1.1
Content-Type: application/json

{
  "name": "Alice Smith",
  "email": "alice.smith@example.com"
}

# Update a reviewer
###
PUT https://ash-book-review.onrender.com/reviewers/669b0c55baea3bce90b95621 HTTP/1.1
Content-Type: application/json

{
  "name": "Alice Johnson",
  "email": "alice.johnson@example.com"
}

# Delete a reviewer
###
DELETE https://ash-book-review.onrender.com/reviewers/669b10327f1f895083df1136 HTTP/1.1
