# Get all reviews
GET https://ash-book-review.onrender.com/reviews HTTP/1.1

# Get a single review by ID
###
GET https://ash-book-review.onrender.com/reviews/{id} HTTP/1.1

# Create a new review
###
POST https://ash-book-review.onrender.com/reviews HTTP/1.1
Content-Type: application/json

{
  "bookId": "669b16bf3163e859ed34123a",
  "reviewerId": "605c72ef2f8fb814a8bde898",
  "rating": 5,
  "comment": "A gripping and thought-provoking read."
}

# Update a review
###
PUT https://ash-book-review.onrender.com/reviews/669b0d6baf8ede6f5caa2e8f HTTP/1.1
Content-Type: application/json

{
  "bookId": "605c72ef2f8fb814a8bde897",
  "reviewerId": "605c72ef2f8fb814a8bde898",
  "rating": 5,
  "comment": "A fascinating read with a few slow moments."
}

# Delete a review
###
DELETE https://ash-book-review.onrender.com/reviews/{id} HTTP/1.1

